name: Build APK Denjaka SOC
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Essential Tools
        run: |
          sudo apt update
          # Kita hanya pasang yang benar-benar wajib untuk Buildozer
          sudo apt install -y build-essential git python3-dev zip unzip zlib1g-dev libffi-dev libssl-dev
          pip install --user --upgrade buildozer cython virtualenv

      - name: Build with Buildozer
        run: |
          export PATH=$PATH:$HOME/.local/bin
          # Kita pakai perintah 'yes' agar otomatis melewati pertanyaan lisensi
          yes | buildozer android debug
          
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: bin/*.apk
